### ISSUE TITLE
Show class labels in the cell along the diagonal

### ISSUE THREAD

**Issue by mstreit** [Caleydo/malevo#102]
Empty cells along the diagonal can be confusing, in particular for the heatmap cell encoding where cells with small values are also white.

![image](https://user-images.githubusercontent.com/4129755/38028490-5d74da30-3293-11e8-9a9b-c4ef5ec71497.png)

**Comment by NMO13** [comment]
Duplicate: https://github.com/Caleydo/malevo/issues/73

**Comment by thinkh** [comment]
Closed. Use #73.
