### ISSUE TITLE
add interface to toggle training and test runs (e.g. checkbox)

### ISSUE THREAD

**Issue by gfrogat** [Caleydo/malevo#107]
We should add controls to toggle train and test performance for a run. Handling them as separate datasets is not ideal, as you have always select the corresponding datasets if you want to view it.

**Comment by thinkh** [comment]
Example: 

![grafik](https://user-images.githubusercontent.com/5851088/38999536-595a807e-43f2-11e8-9c16-e95f88f5e512.png)

**Comment by gfrogat** [comment]
This will be addressed by the new run/fold selector.
