### ISSUE TITLE
Change image background to transparent

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#117]
I think the images in the sprites are always ordered as a nx10 matrix right?
If the sprite cannot be filled with images, then black images will be added as placeholder right?

E.g.
![image](https://user-images.githubusercontent.com/3988444/39117978-855586e4-46e8-11e8-81e0-baf56968116a.png)

I think this looks a bit misleading because the user may not know if the black placeholder images are "real" images at first glance. I would suggest we make these images transparent so they don't show up at all.

**Comment by thinkh** [comment]
The best solution would be to [make the background transparent](https://stackoverflow.com/a/4380602) and implement it here: https://github.com/Caleydo/malevo/blob/3d1186d0dae888ac1d0221b80dadf03ba0a9f0ae/malevo/api.py#L116

**Comment by thinkh** [comment]
Done.

![image](https://user-images.githubusercontent.com/5851088/39135467-4ce7142c-4719-11e8-9ca4-563314f32bcd.png)
