### ISSUE TITLE
Add selected epoch to image detail view

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#118]
Add the selected single epoch to the label to indicate which images are shown. 

![grafik](https://user-images.githubusercontent.com/5851088/39122741-2089b01a-46f6-11e8-82fd-ac154884fdf0.png)

**Comment by thinkh** [comment]
Out of scope for the paper. Hence, moved to icebox.

**Comment by gfrogat** [comment]
we decided not to implement any task specific views (i.e. showing instances such images)

can we close this?
