### ISSUE TITLE
Add columns/rows for performance measures on demand

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#124]
The user wants to add further columns on demand:

* As row
  * False positive rate (show as default)
* As column
  * False negative rate (show as default)
  * Accuracy (show as default)
  * Class size (show as default when not homogenous)
  * Precision
  * Recall
  * F1
  * [ROC curve](https://en.wikipedia.org/wiki/Receiver_operating_characteristic)

**Comment by gfrogat** [comment]
We should sketch the whole interaction and interface first before implementing this.

Also should it be possible to reorder the columns?

**Comment by gfrogat** [comment]
not relevant anymore due to new MetricsView
