### ISSUE TITLE
Change background color of run name in selector

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#130]
The background of the run name should be color encoded rather than the text.
This should help alleviating perceptional issues.

![image](https://user-images.githubusercontent.com/3988444/39126497-e281f5cc-4702-11e8-80c6-3a498766d253.png)

**Comment by mstreit** [comment]
As we decided to have one timeline only, the dataset label should be colored in the selection chooser.

**Comment by NMO13** [comment]
Ok makes sense.
