### ISSUE TITLE
malevo as single Docker container

### ISSUE THREAD

**Issue by gfrogat** [Caleydo/malevo#137]
deployment is currently realized via Docker. We should try to simplify the setup process by bundling malevo + deps in a pip package.

**Comment by thinkh** [comment]
We agreed that creating a pip package is too much effort and not so easy to implement with all the Phovea Python dependencies. Therefore, we will build and publish a single Docker container that a user can "install" and run.

The docker container must contain:

* Phovea server
* Malevo server
* Malevo frontend (already build)
* Mounted host directory into data directory

**Comment by gfrogat** [comment]
We talked about moving the data loading into a separate API to be backend agnostic, and to be able to simplify the data loading via a Python package.

The user would simply download the prebuilt docker container and start a local data server (i.e. a python package).

By doing that we can support multiple backends and don't have to mess with `phovea_server`.

**Comment by gfrogat** [comment]
now possible thanks to changes + new docker-compose file from @thinkh
