### ISSUE TITLE
Provide installation documentation

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#139]
The installation documentation targets new users that wants to use malevo to visualize their run data.

The documentation must contain the following parts:

- [ ] Data preperation (how to modify the data flow)
- [ ] Prerequisits
- [ ] Installation steps
- [ ] Tutorials

The documentation should be added to the README.md and the Wiki

**Comment by gfrogat** [comment]
As we only work an a minimal feasible version for the paper, is this still relevant?

**Comment by gfrogat** [comment]
Installation and usage documentation will be incrementally added.

**Comment by gfrogat** [comment]
We created a simple Python package that also contains the frontend. Installation via `pip install` and documented in the separate repo.
