### ISSUE TITLE
Work on paper stories 

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#147]
* Generalization of ML
* Hyper parameter influence on model selection
* Replication of notable other papers (Sharp Minima, Small Batch Learning, ...)

**Comment by NMO13** [comment]
@gfrogat What is generalization of ML? And what is Sharp Minima? And which papers are available that we can replicate?

**Comment by gfrogat** [comment]
- Generalization of ML should be "model generalization error"
- sharp minima: have a look at the paper Marc linked

**Comment by gfrogat** [comment]
Paper story: Tool allows for comparison of performance between models and across multiple dataset folds.

Main focus is generalization error of model.
