### ISSUE TITLE
Plot results scaled to percentage not the actual values

### ISSUE THREAD

**Issue by gfrogat** [Caleydo/malevo#150]
When comparing train and test results of a specific parametrization the line charts should show the changes in percent -- currently we show the absolute values. If the training set is larger the training set curves will be naturally higher.

![image](https://user-images.githubusercontent.com/11089303/39986606-7949d384-5762-11e8-9996-cd821823a22f.png)

**Comment by NMO13** [comment]
We could add a toggle button in order to change between absolute and percentage values.

**Comment by NMO13** [comment]
Using percentages is actually pretty cool.
For example, some train/test runs are having the same precision pattern, as I have writte in my slideset.
But when using percentage scaling, it becomes obvious that not only the precision curves have the same pattern but all the confusion matrix cells as well.
E.g. 
![image](https://user-images.githubusercontent.com/3988444/40124760-8beb858c-5929-11e8-9c86-f5927581ca03.png)

**Comment by mstreit** [comment]
yes, very nice!

**Comment by gfrogat** [comment]
We should only show the option to switch between "actual" and percentage scaling if all runs have the same number of items per class (i.e. only comparing train vs train or test vs test). Otherwise percentage scaling should be the default.

**Comment by thinkh** [comment]
Done with PR #159.
