### ISSUE TITLE
Show class size for multiple runs

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#155]
At the moment we only show the class size of the first run. However, if multiple selected runs have a different class size (e.g., test and train) this information is wrong.

![image](https://user-images.githubusercontent.com/5851088/39987125-1d2827de-5764-11e8-8f0b-e251cdee7145.png)

**Possible solutions**

* Split cell in two (or more) rows, similar to the heatmap cells and note the size
* OR encode the class size as histogram (bar chart)

**Comment by NMO13** [comment]
Yes that makes sense.

**Comment by thinkh** [comment]
Done with PR #155.
