### ISSUE TITLE
Observed usability flaws 

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#156]
- Selecting spikes in detail view should be possible in order to change single selector
- The x-axis tick marks are overlapping => hard to find desired epoch
- Selecting datasets is very cumbersome (e.g. selecting same run with only different learning rate
  needs to scroll through the whole list)
- Showing class size for each run separately
- Calculate mean precision over all classes in order to estimate best run and model
- app performance for 1 epoch granularity is bad
- show loading icon if loading takes long
- show correctly classified images as heatmaps (not just misclassified images)
- Single epoch marker is currently not very helpful
- I didn't use the range selector of the timelines because I just needed to see an overall view
- Accuracy is missing
- For comparing a broader range of parameters, it would be helpful to have more than 4 runs selectable
- Altering the timeline selection resets the detail view which is annoying
- Digging deeper:
  + I want to know which images are misclassified. Are always the same images misclassified if oscillation is high?
  + Why gets an image mispredicted? Which layers/filters are causing mispredictions?

**Comment by mstreit** [comment]
That's very useful. Can you please also propose solutions and point to the corresponding tickets (or create one if there is none)?

**Comment by NMO13** [comment]
Yes I do when I have time.

**Comment by gfrogat** [comment]
> - show loading icon if loading takes long

do you mean the initial loading of the data or also when updating the views?

> - show correctly classified images as heatmaps (not just misclassified images)

I don't get this, what do you mean by that?

**Comment by NMO13** [comment]
> do you mean the initial loading of the data or also when updating the views?
The initial loading of datasets. The timelines could blink (similar to blinking stacked bar charts in taco)
But you are right with saying updating views: When the detail views need to load something then we need a similar concept.

> show correctly classified images as heatmaps (not just misclassified images)
Ja during playing around I noticed that I want to see if there are patterns in the diagonal as well.
But I am not sure if this is really important. Supposedly not.

**Comment by thinkh** [comment]
I just noticed that this is the epic. We should wait until all depending issues have been closed.

**Comment by thinkh** [comment]
I will close this epic, because of the issues are already implemented.
