### ISSUE TITLE
The x-axis tick marks are overlapping

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#164]
The x-axis tick marks are overlapping => hard to find desired epoch

![image](https://user-images.githubusercontent.com/3988444/40358259-eb9a7990-5dbe-11e8-85bd-cc44b5746515.png)

**Comment by thinkh** [comment]
Related issue: #180.

**Comment by NMO13** [comment]
Should be fixed.

**Comment by NMO13** [comment]
Is that okay?
![image](https://user-images.githubusercontent.com/3988444/42441078-aea76aec-8367-11e8-99af-98e49842c5cb.png)

**Comment by thinkh** [comment]
For this case it looks fine. Does this still work for fewer epochs (i.e., that the gaps are not so large)?

**Comment by gfrogat** [comment]
How are the breaks computed?

**Comment by thinkh** [comment]
Done with PR #205.
