### ISSUE TITLE
App performance for 1 epoch granularity runs is bad

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#167]
Just try it, you will notice.

1. The dataloading takes long.
2. The frontend part needs to be optimized.

**Comment by thinkh** [comment]
@NMO13 Is this relevant for the paper? Can you make suggestions for improvements?

**Comment by thinkh** [comment]
Possible workaround is a loading icon as suggested in #168

**Comment by thinkh** [comment]
Might get better with new backend.

**Comment by gfrogat** [comment]
new backend and removal of the SingleEpochMarker drastically improved the performance.

We still need to discuss whether the SingleEpochMarker is needed or whether we attempt to refactor the code to improve the performance.

@thinkh said he would have a look at it

**Comment by gfrogat** [comment]
Performance improved a lot thanks to changes by @thinkh
