### ISSUE TITLE
Remove detail view tabs

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#182]
Since we do not have a class changer view we can remove the tabs for the detail views.

![image](https://user-images.githubusercontent.com/5851088/41281571-01e9bcc8-6e32-11e8-9622-5e5c778dead8.png)

**Comment by NMO13** [comment]
How about this?
![capture](https://user-images.githubusercontent.com/3988444/42158815-dc5f392c-7df1-11e8-96a8-aab0af095041.PNG)

**Comment by mstreit** [comment]
Looks good. 'Charts' is not a good title though. I suggest to have a more descriptive title that describes which cell/plot the user has selected and what is shown in the plot.

**Comment by NMO13** [comment]
You are right, the charts label is completely useless. I will leave this and the horizontal line away. and make the cell name bigger.

**Comment by NMO13** [comment]
Okay?
![image](https://user-images.githubusercontent.com/3988444/42164214-9fce7464-7e05-11e8-9b99-81177330dcb0.png)

**Comment by mstreit** [comment]
Looks good to me!

**Comment by thinkh** [comment]
Done with PR #190.
