### ISSUE TITLE
rename Malevo to ConfusionFlow

### ISSUE THREAD

**Issue by gfrogat** [Caleydo/malevo#183]

**Comment by thinkh** [comment]
Do we want to rename everything?

Including:

- [ ] Repository
- [ ] App name in header
- [ ] Caleydo App URL

**Comment by gfrogat** [comment]
As we'll move to a different repo in the future anyway we could keep malevo as repo name for now but the other stuff should definitely be changed.

**Comment by NMO13** [comment]
I would suggest that too. Its very common in software projects to have working titles in repo names etc.

**Comment by thinkh** [comment]
Renamed the app title with commit b07ddf30dab7fec0f742e156d5bd54d5f74d5d1f. The deployment is available at: https://confusionflow.caleydoapp.org
