### ISSUE TITLE
Which cells should be affected by the scaling slider?

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#195]
Currently, the matrix cells (without additional matrix cells)  + detail view is scaled when the slider is dragged. Should the additional matrix cells be scaled as well?

**Comment by gfrogat** [comment]
What additional matrix cells are you talking about?

**Comment by NMO13** [comment]
The precision, recall, F1 score columns

**Comment by gfrogat** [comment]
It doesn't make sense to scale them with the confmat cells as they encode different measures on the y-axis.

**Comment by NMO13** [comment]
Yes makes sense. Then we only scale the confmat cells.
