### ISSUE TITLE
Click between two epochs in timeline removes highlight

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#22]
### Steps to reproduce

1. Click between two epochs

![malevo-timline-highlight](https://user-images.githubusercontent.com/5851088/35741271-ad25e7b2-0837-11e8-86ff-a678daeeea8f.gif)

### Observed behavior
No epoch is highlighted, but also no event is fired to load a different epoch.

### Expected behavior
The highlight should stay consistent and not be removed. Or if removed, then the loaded data in matrix must be removed, too.

**Comment by NMO13** [comment]
Some other related bugs:
1. Clicking a small range deselects single epoch:
![bug](https://user-images.githubusercontent.com/3988444/36146737-e388a0de-10b5-11e8-86ee-01e2e8d5f671.gif)

**Comment by thinkh** [comment]
Done with last PR.
