### ISSUE TITLE
Add state management or model

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#23]
With the growing the number of data and components in the frontend we should think and implement some kind of state management. For instance, the matrix data and labels are loaded in the ConfusionMatrix class, but I need to access this data in a detail view as well. So I can pass this data via events around, but that is not the optimal case. So we need some kind of model where we store the data and we can access it from everywhere. 

One option would be to use/implement [Redux](https://redux.js.org/) (without react) as described in [this article](https://www.sitepoint.com/redux-without-react-state-management-vanilla-javascript/).

@NMO13 What do you think?

**Comment by NMO13** [comment]
Yes cool. I'll have a look at Redux asap.

**Comment by NMO13** [comment]
I think we should create our own store. I have already started to do that in https://github.com/Caleydo/malevo/pull/50

**Comment by thinkh** [comment]
On-going implementation.
