### ISSUE TITLE
Encode the number of classifications in the cell size of the conf matrix 

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#26]
![grafik](https://user-images.githubusercontent.com/5851088/35865364-996c03da-0b54-11e8-8628-2ddd114a7836.png)

**Comment by thinkh** [comment]
Basically done. Improvement would be scale the area visually perceptual.

**Comment by mstreit** [comment]
I don't think that this is the optimal solution already because the activity in small classes is now almost invisible.

**Comment by gfrogat** [comment]
yes I agree, we need to find a good mapping from cell values to the size and color of the cells:

## colorscale
the colorscale should also be adapted to highlight the small cells. 

- Below I messed around with purple and orange but something like the [mpl colormaps](https://bids.github.io/colormap/) would be nice. (As the mpl maps are not included in d3v3 I wrote something myself.)
![screen shot 2018-02-06 at 18 56 53](https://user-images.githubusercontent.com/11089303/35876103-91efce8a-0b71-11e8-81a7-d000b9bd1b13.png)

- mpl magma version
![screen shot 2018-02-06 at 20 30 33](https://user-images.githubusercontent.com/11089303/35879912-bd1b8012-0b7c-11e8-9433-737d4c2b75d2.png)

- mpl viridis version
![screen shot 2018-02-06 at 20 42 47](https://user-images.githubusercontent.com/11089303/35880486-63b335c2-0b7e-11e8-9882-f110a79df59b.png)


## area scaling
the area scaling should also be perceptually correct. 

- linear scaling (current version)
![screen shot 2018-02-06 at 20 34 38](https://user-images.githubusercontent.com/11089303/35880102-43cffb24-0b7d-11e8-84b2-ad475f2c0b8c.png)

- area scaling
![screen shot 2018-02-06 at 20 34 01](https://user-images.githubusercontent.com/11089303/35880118-5126d536-0b7d-11e8-8db8-534484366a20.png)

**Comment by NMO13** [comment]
When you select multi epochs + single epoch then you cannot show the spark lines properly because its hard to visually differentiate betw. rectangles and spark lines. Using our original approach of using the full area (without scaling) for multi epochs and scaling with single epochs would lead to inconsistencies in the design.

**Comment by mstreit** [comment]
Yes, I agree that we should have a consistent encoding between single and multi epoch. 

But I still like the possibility of encoding a second value in each cell using a bar shown at the bottom of each cell - similar to what we have in each StratomeX block. 

![image](https://user-images.githubusercontent.com/4129755/36101173-d9f73bc8-1008-11e8-8457-77cbf68e4a1c.png)

**Comment by NMO13** [comment]
I will close that issue for now since we currently have no use case for a bar at the bottom. When we have one, we will make a separate issue for that.
