### ISSUE TITLE
Live updates after each epoch (support monitoring)

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#33]

**Comment by gfrogat** [comment]
I’ll look into this over the next weeks when refactoring the data loading.

**Comment by gfrogat** [comment]
live updates will require a way to send updates to the client, e.g. via [Websockets](https://developer.mozilla.org/en-US/docs/Web/API/Websockets_API)

I'll discuss the architecture and requirements with @NMO13 and @thinkh over the next days.

**Comment by gfrogat** [comment]
Won't be supported by current version. It's only possible to view completed runs.
