### ISSUE TITLE
switching between datasets doesn't completely update epoch timeline

### ISSUE THREAD

**Issue by gfrogat** [Caleydo/malevo#34]
<img width="646" alt="screen shot 2018-02-09 at 16 24 35" src="https://user-images.githubusercontent.com/11089303/36035040-181f4422-0db6-11e8-8953-0002214604d5.png">

**Comment by thinkh** [comment]
Fixed with https://github.com/Caleydo/malevo/pull/32/commits/73988110a19ee4056db207f09713f47210f7ff64#diff-877c9dd258d3b4d4344a1ca43b3ffc0cR28
