### ISSUE TITLE
timeline selection persists on dataset change

### ISSUE THREAD

**Issue by gfrogat** [Caleydo/malevo#35]
![feb-09-2018 16-40-49](https://user-images.githubusercontent.com/11089303/36035729-0c1397ee-0db8-11e8-8e51-ef3e58cfe625.gif)

**Comment by NMO13** [comment]
Haha looks funny ;)

**Comment by NMO13** [comment]
This bug is obsolete, however this one is still here:
![bug](https://user-images.githubusercontent.com/3988444/36146865-4fd98d48-10b6-11e8-8f07-bd4576c390b0.gif)

**Comment by thinkh** [comment]
Done with last PR.
