### ISSUE TITLE
Create accurarcy column for one epoch

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#4]
![image.png](https://images.zenhubusercontent.com/599562848f62dc7798c31c64/9aa12d42-4cee-4aba-b7ca-a091faffbbe1)

**Comment by NMO13** [comment]
What we actually want is the precision and not the accuracy The accuracy is a measure of the overall performance of a classifier whereas the precision is a measure for comparing classifications of classes with each other.

**Comment by thinkh** [comment]
Done with PR #24.
