### ISSUE TITLE
Create Sliding Window

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#40]
It should be possible to drag the selected epoch range by mouse. This alleviates the selection of epoch ranges.

for example:

1.
![image.png](https://images.zenhubusercontent.com/5993f73b8f62dc7798c2f349/b0aa6204-a8a6-4295-8960-a92718aecc45)

2.
![image.png](https://images.zenhubusercontent.com/5993f73b8f62dc7798c2f349/7883785b-9162-4f55-8b54-a4c197b9fb1a)

3.
![image.png](https://images.zenhubusercontent.com/5993f73b8f62dc7798c2f349/eb81cdc6-d964-4903-9c63-bf981540baa3)

So the range should stay constant but the selected epochs should be changeable.

**Comment by gfrogat** [comment]
would this also include the possibility to expand the current selection?

i.e. drag the right end of the selection band to include new epochs:

![image](https://user-images.githubusercontent.com/11089303/37271967-68e569cc-25d5-11e8-8850-dccfddbcffb8.png)

![image](https://user-images.githubusercontent.com/11089303/37271973-6d5b7fbe-25d5-11e8-9b2b-24a475d8a4e0.png)

**Comment by NMO13** [comment]
Yes of course.
This issue is related to https://github.com/Caleydo/malevo/issues/63#issuecomment-372254241
