### ISSUE TITLE
Create timeline for one dataset

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#5]
Must support:

- [ ] show multiple timepoints for one dataset
- [ ] selection of one timepoint
- [ ] selection of a time range 

Send selection as event so that other components can listen.

![image.png](https://images.zenhubusercontent.com/599562848f62dc7798c31c64/9e7d9e95-bb01-496b-8b75-38432db7c242)

**Comment by mstreit** [comment]
@NMO13, please always post a screenshot when closing a feature issue so that the rest of the team can provide feedback. 
Alternatively, we can create a version that will be deployed on AWS. I will create an issue for this.

**Comment by NMO13** [comment]
I have added a screenshot to the pull request.

**Comment by NMO13** [comment]
Okay I have forgotten it. Did it now.
