### ISSUE TITLE
Find examples with different class size

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#60]
So that we don't have only the 5000 images from the CIFAR10 dataset. How would that effect the scoring and comparison?

![grafik](https://user-images.githubusercontent.com/5851088/39001944-c00252f2-43f7-11e8-9816-15fb4fca4d14.png)

**Comment by thinkh** [comment]
[F1 score](https://en.wikipedia.org/wiki/F1_score) might be a measure that we can use.

**Comment by gfrogat** [comment]
We support now percentage scaling and can handle different class sizes.
