### ISSUE TITLE
Improved multi-dataset timeline

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#63]
No-one has noticed so far, that the timeline becomes very long and hard to handle:

![image.png](https://images.zenhubusercontent.com/5993f73b8f62dc7798c2f349/34a3bf7d-8d1e-4edf-80af-5821cc3b76e1)

Therefore we should use a more compact form or even use d3 scale. https://bl.ocks.org/mbostock/34f08d5e11952a80609169b7917d4172

**Comment by mstreit** [comment]
We agreed with @NMO13 and @thinkh to use native d3 axes. Same epochs across the datasets should align horizontally. This way we can also use the native sliding d3 window brush. The selected epoch will be the end of the window by default, however, the user can set the epoch selection to a different epoch by clicking on the timeline. Note that the selected epoch and the selected window can be different for the selected datasets.

**Comment by thinkh** [comment]
Examples for brush snapping:

* https://bl.ocks.org/mbostock/b0d0aa4df3b5c3c0fa37d4b3f2127740
* https://bl.ocks.org/mbostock/6232620
* https://bl.ocks.org/mbostock/6232537
