### ISSUE TITLE
Prepeare softmax data for softmax heatmap

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#67]
Calculate softmax activation from pre-softmax activation. Value between [0,1].

The API is defined in the [swagger.yml](https://github.com/Caleydo/malevo/blob/gfrogat/features/api/malevo/swagger.yml#L186)

**Comment by gfrogat** [comment]
I encountered major scalability problems that have to be addressed first.

The combined database for all current runs would be +10 GB large. Alternatives are discussed in #27

**Comment by gfrogat** [comment]
the discussion moved to #27 

I'll close this issue.
