### ISSUE TITLE
Create list of experiments that we need for the paper

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#69]
We need to come up with a list of experiements that we need for the paper soon, because the computation needs some time.

**Comment by mstreit** [comment]
Experiments to compare different:
- [ ] models
 optimization functions
- [ ] hyperparameter configurations
- [ ] batch sizes / datasets
- [ ] seeds
- [ ] machines?

@gfrogat, can you please further specify what runs you plan to perform exactly.
@HendrikStrobelt any news on the hardware / processing cluster issue?

**Comment by gfrogat** [comment]
## resnet34, adam
- [ ] `resnet34, adam, lr=0.1 , batch_size = 128`
- [ ] `resnet34, adam, lr=0.01, batch_size = 128`
- [ ] `resnet34, adam, lr=0.1 , batch_size = 256`
- [ ] `resnet34, adam, lr=0.01, batch_size = 256`
- [ ] `resnet34, adam, lr=0.1 , batch_size = 512`
- [ ] `resnet34, adam, lr=0.01, batch_size = 512`

## resnet34, sgd
- [ ] `resnet34, sgd, lr=0.1 , momentum=0.9, batch_size = 128`
- [ ] `resnet34, sgd, lr=0.01, momentum=0.9, batch_size = 128`
- [ ] `resnet34, sgd, lr=0.1 , momentum=0.8, batch_size = 128`
- [ ] `resnet34, sgd, lr=0.01, momentum=0.8, batch_size = 128`
- [ ] `resnet34, sgd, lr=0.1 , momentum=0.7, batch_size = 128`
- [ ] `resnet34, sgd, lr=0.01, momentum=0.7, batch_size = 128`
- [ ] `resnet34, sgd, lr=0.1 , momentum=0.9, batch_size = 256`
- [ ] `resnet34, sgd, lr=0.01, momentum=0.9, batch_size = 256`
- [ ] `resnet34, sgd, lr=0.1 , momentum=0.8, batch_size = 256`
- [ ] `resnet34, sgd, lr=0.01, momentum=0.8, batch_size = 256`
- [ ] `resnet34, sgd, lr=0.1 , momentum=0.7, batch_size = 256`
- [ ] `resnet34, sgd, lr=0.01, momentum=0.7, batch_size = 256`
- [ ] `resnet34, sgd, lr=0.1 , momentum=0.9, batch_size = 512`
- [ ] `resnet34, sgd, lr=0.01, momentum=0.9, batch_size = 512`
- [ ] `resnet34, sgd, lr=0.1 , momentum=0.8, batch_size = 512`
- [ ] `resnet34, sgd, lr=0.01, momentum=0.8, batch_size = 512`
- [ ] `resnet34, sgd, lr=0.1 , momentum=0.7, batch_size = 512`
- [ ] `resnet34, sgd, lr=0.01, momentum=0.7, batch_size = 512`


## vgg19, adam
- [ ] `vgg19, adam, lr=0.1 , batch_size = 128`
- [ ] `vgg19, adam, lr=0.01, batch_size = 128`
- [ ] `vgg19, adam, lr=0.1 , batch_size = 256`
- [ ] `vgg19, adam, lr=0.01, batch_size = 256`
- [ ] `vgg19, adam, lr=0.1 , batch_size = 512`
- [ ] `vgg19, adam, lr=0.01, batch_size = 512`
 
## vgg19, sgd
- [ ] `vgg19, sgd, lr=0.1 , momentum=0.9, batch_size = 128`
- [ ] `vgg19, sgd, lr=0.01, momentum=0.9, batch_size = 128`
- [ ] `vgg19, sgd, lr=0.1 , momentum=0.8, batch_size = 128`
- [ ] `vgg19, sgd, lr=0.01, momentum=0.8, batch_size = 128`
- [ ] `vgg19, sgd, lr=0.1 , momentum=0.7, batch_size = 128`
- [ ] `vgg19, sgd, lr=0.01, momentum=0.7, batch_size = 128`
- [ ] `vgg19, sgd, lr=0.1 , momentum=0.9, batch_size = 256`
- [ ] `vgg19, sgd, lr=0.01, momentum=0.9, batch_size = 256`
- [ ] `vgg19, sgd, lr=0.1 , momentum=0.8, batch_size = 256`
- [ ] `vgg19, sgd, lr=0.01, momentum=0.8, batch_size = 256`
- [ ] `vgg19, sgd, lr=0.1 , momentum=0.7, batch_size = 256`
- [ ] `vgg19, sgd, lr=0.01, momentum=0.7, batch_size = 256`
- [ ] `vgg19, sgd, lr=0.1 , momentum=0.9, batch_size = 512`
- [ ] `vgg19, sgd, lr=0.01, momentum=0.9, batch_size = 512`
- [ ] `vgg19, sgd, lr=0.1 , momentum=0.8, batch_size = 512`
- [ ] `vgg19, sgd, lr=0.01, momentum=0.8, batch_size = 512`
- [ ] `vgg19, sgd, lr=0.1 , momentum=0.7, batch_size = 512`
- [ ] `vgg19, sgd, lr=0.01, momentum=0.7, batch_size = 512`

**Comment by HendrikStrobelt** [comment]
@gfrogat I will take care of this soon. Not sure if before VIS deadline though.

**Comment by gfrogat** [comment]
@HendrikStrobelt do you have any updates on the runs? Thanks!

Based on the discussion with Sepp: Should we focus on CIFAR 100? Malevo currently cannot deal with the hierachical classes yet, but the behaviour of simple classifier for the superclasses might be interesting.

**Comment by thinkh** [comment]
@HendrikStrobelt What is the status here? Could you please provide some updates.

**Comment by thinkh** [comment]
I created an epic for CIFAR 100 with smaller issues (see https://github.com/Caleydo/malevo/issues/112).

**Comment by thinkh** [comment]
Waiting for data upload from @HendrikStrobelt. Afterwards we can close this issue.

**Comment by thinkh** [comment]
Done.
