### ISSUE TITLE
Combine multiple and single epoch

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#7]
* Add dashed line to matrix cells

The rest should be availalbe with #2, #3, #4, #5, #6

![image.png](https://images.zenhubusercontent.com/599562848f62dc7798c31c64/9c3c76f4-f72e-40a8-8584-487571618e74)

**Comment by NMO13** [comment]
@thinkh and me decided to use dashed lines because using dots would not work for multi-line charts.
Please provide some feedback to that:
![image](https://user-images.githubusercontent.com/3988444/36161203-62417626-10e3-11e8-9e84-afca8717311e.png)

**Comment by mstreit** [comment]
very nice, good work!

note to ourselves: if we want to stick to the orange color for the selected epoch, we should avoid it in the classes.

**Comment by mstreit** [comment]
actually the style of the timeline in the sketch posted above does not look to bad. I like the style with the filled circle for the selected epoch.

**Comment by thinkh** [comment]
@mstreit Yes, with the selection color you are correct.

**Comment by thinkh** [comment]
Switching to gray for the selection line in the matrix is also not an option, when we use the grayscale for the background-color at the same time. So we have to find a color anyway. :)

**Comment by mstreit** [comment]
That's true. But in the background (heatmap) it is used to encode a data value, which cannot be confused with a class.

**Comment by mstreit** [comment]
will the version posted above be integrated in the deployed version? I would like to try it out with the new datasets.

**Comment by thinkh** [comment]
Done with last PR. It will be deployed tomorrow morning.
