### ISSUE TITLE
Remove 'epoch' label from timeline and linechart for each individual epoch

### ISSUE THREAD

**Issue by mstreit** [Caleydo/malevo#79]
Showing 'Epoch' once along the axis of the line chart and at the beginning of the timeline at the top is sufficient. 

![image](https://user-images.githubusercontent.com/4129755/37141782-76a8d39a-22b6-11e8-8393-364af8ba0fc7.png)
![image](https://user-images.githubusercontent.com/4129755/37141791-7bca9462-22b6-11e8-91d9-3f52955cca2f.png)

**Comment by thinkh** [comment]
Obsolete with new timeline.
