### ISSUE TITLE
Create diff visualizations for confmat cells

### ISSUE THREAD

**Issue by NMO13** [Caleydo/malevo#88]
Related to https://github.com/Caleydo/malevo/issues/65

Implement difference visulizations for 
- single line charts
- multi line charts
- barcharts
- heatmaps

**Comment by thinkh** [comment]
Single line charts, multi line charts and heatmaps are implemented with PR #108. The only thing left are the bar charts.

Close this issue and open a specific issue for the bar chart implementation.
