### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by gfrogat** [Caleydo/malevo#90]
Should we aim to also fully test Malevo on Firefox?

**Comment by gfrogat** [comment]
@NMO13 did you already implement any Selenium tests?

**Comment by thinkh** [comment]
Yes, we should support Firefox. Eventhough I wouldn't see it as top priority. In general there shouldn't be so much difference.

**Comment by NMO13** [comment]
No currently there are no Selenium tests

**Comment by gfrogat** [comment]
Current app is Chrome only. Rewrite will consider Firefox.
