### ISSUE TITLE
paper prototypes - update with new ideas

### ISSUE THREAD

**Issue by gfrogat** [Caleydo/malevo#91]
create paper prototypes for new views:
- softmax stamp, #27
- instance loss, #27
- histogram, #86
- embedding of instances
- class hierarchy
- visualization of gradients (high loss =?= high gradients)
- generalization to multi-task learning
- class changer visualization, #84 
- detail view, confmat interaction, #83, #47
- diff visualization for heatmap, #88, #75
- difference ingoing / outgoing class combination, #38 
- view interaction
- adapt detail views to hierarchical class problem
- data driven detail views (e.g. only show softmax stamps if there's actually data, otherwise show instructions how to use it)

also discuss alternatives that are very likely unfeasible and should be only pursued if there's a need by the users:
- feature visualization of model in different epoch

**Comment by thinkh** [comment]
@gfrogat and @NMO13 Is this still open or already done with the consolidated presentation?

**Comment by gfrogat** [comment]
nope, we should discuss this tomorrow if possible

**Comment by thinkh** [comment]
@gfrogat Is this still open?

**Comment by gfrogat** [comment]
Created a Milestone for the Paper Prototypes + Requirements for the paper.

Feel free to add relevant issues.

**Comment by gfrogat** [comment]
closed with Vis Grammar in Google Drive
