### ISSUE TITLE
New category color encoding 

### ISSUE THREAD

**Issue by thinkh** [Caleydo/malevo#93]
* Make category color grey by default
* Apply color only on selection or hover a cell

![grafik](https://user-images.githubusercontent.com/5851088/37660465-cb73e5cc-2c52-11e8-8433-7c5cdcc5280f.png)

**Comment by mstreit** [comment]
Will be important for the multi condition (dataset) comparison

**Comment by thinkh** [comment]
Notes on that from today's meeting:

* Every added dataset gets a unique color
* Categories in the conf matrix should be grey
* Hovering/selecting a cell will assign two colors to ground truth and predicted category

**Comment by mstreit** [comment]
The single epoch indicator line in the multi epoch case can be a black or gray dotted 1px line. (remove orange). Agreed?
