### ISSUE TITLE
Single epoch multi dataset encoding

### ISSUE THREAD

**Issue by mstreit** [Caleydo/malevo#94]
As discussed yesterday in the call, dividing the confusion matrix cells in multiple areas is not optimal for the multi condition (dataset) comparison.

I suggest to switch to a simple line encoding (like a fuel bar) for the single epoch case where the line style represents the condition (e.g., DS1 = line, DS2 = stippled line, DS3 = dotted line). 

This also has the advantage that the single epoch encoding would be very similar to the multi epoch encoding in the confusion matrix cells. This way, the user does not need to switch the mental model.

![image](https://user-images.githubusercontent.com/4129755/37704773-199c03e0-2cfa-11e8-90a9-32df0873e10f.png)
(I've updated the sketch in our GSlide deck accordingly: https://docs.google.com/presentation/d/1G5E-HJ_PRDsJ90YH6vd2Kf4L6wR-_SjkRns3BUD8u5g/edit#slide=id.g3445cf67de_0_13)

@HendrikStrobelt, @NMO13, @thinkh, @gfrogat: do you agree?

**Comment by gfrogat** [comment]
looks good to me, but we'll very likely encounter scaling issues assuming that all the cells will have the same range on the y-axis (we'll probably have some very large "buckets" and the remaining lines will be squashed at the bottom)

**Comment by mstreit** [comment]
might be the case, yes. but was that different in our color encoding (one dark cell, rest almost white)?

**Comment by NMO13** [comment]
Hendrik proposed the idea of adding a slider that controls the y range of the cells. This allows interactive "zooming". Squashed lines at the bottoms are easier to recognize this way. I think its not a bad idea.

**Comment by gfrogat** [comment]
how about this:

![image](https://user-images.githubusercontent.com/11089303/37705229-9a134f78-2cfb-11e8-8298-65b84c0c6e09.png)

**Comment by mstreit** [comment]
yes, that looks good. the single epoch case remains the same, right?

**Comment by gfrogat** [comment]
I thought about combining it, but we can also keep it as separate plot and only use the dotted slider for the transition

**Comment by mstreit** [comment]
How about this?

![image](https://user-images.githubusercontent.com/4129755/37708417-e1e68094-2d06-11e8-84aa-ffb9278b09d1.png)

**Comment by mstreit** [comment]
The line stippling / dotting does not work on the small multiples.
We therefore decided to use color for encoding the different datasets. 
dataset1: dark grey
dataset2: qualitative color1
dataset3: qualitative color2
etc.

**Comment by mstreit** [comment]
Alternative to line-based cell encoding would be to use a heatmap. Advantage is that the single epoch case works the same way as the multi epoch case. Datasets/conditions can be stacked vertically within the cell.

![image](https://user-images.githubusercontent.com/4129755/37902985-8d233004-30f6-11e8-800e-4f36935224d1.png)

**Comment by NMO13** [comment]
Would look like this:
![image](https://user-images.githubusercontent.com/3988444/38020989-00473e14-327c-11e8-9994-5e3a00d44245.png)

**Comment by NMO13** [comment]
Not so easy to see small values...

**Comment by mstreit** [comment]
Yes, because they are small. So that should be fine.
@NMO13 will post additional examples.

**Comment by NMO13** [comment]
Here 3 images with 4 timelines selected and with changing epoch range:
![capture](https://user-images.githubusercontent.com/3988444/38026294-ea464b5e-328b-11e8-9fc9-ac98e16f9595.PNG)
![capture1](https://user-images.githubusercontent.com/3988444/38026295-ea6eac7a-328b-11e8-8dba-45ba666d834d.PNG)
![capture2](https://user-images.githubusercontent.com/3988444/38026296-ea90a7f8-328b-11e8-9cd8-139898430239.PNG)

**Comment by NMO13** [comment]
Here images with 8
![capture3](https://user-images.githubusercontent.com/3988444/38026388-345876c2-328c-11e8-8cea-d2e3371a7af0.PNG)
![capture4](https://user-images.githubusercontent.com/3988444/38026389-347bed46-328c-11e8-8edc-6c15039123ca.PNG)

 timelines and varying epoch ranges:

**Comment by mstreit** [comment]
I like it! It's definitely much less cluttered than the line charts.
There are also interesting patterns that become obvious when looking at the visualizations. In this example (https://user-images.githubusercontent.com/3988444/38026296-ea90a7f8-328b-11e8-9cd8-139898430239.PNG), for instance, there is a particular epoch where the peak aligns in the horse predicted column. Seeing similar peak alignments for the ground truth would require to transpose the matrix or at least the cell heatmaps.

**Comment by mstreit** [comment]
@NMO13, can you please also add the old line encoding for the same examples so that we have the direct comparison?

**Comment by NMO13** [comment]
I added the same encoding to the single epoch case:
![image](https://user-images.githubusercontent.com/3988444/38032018-e8bd1fea-329c-11e8-8a8f-a75ed9461842.png)

**Comment by NMO13** [comment]
I added a single epoch marker:
![image](https://user-images.githubusercontent.com/3988444/38091099-cf93f1e2-3364-11e8-83a7-8bc537b7e5c5.png)

**Comment by gfrogat** [comment]
I was initially a little skeptic whether the heatmaps would be useful, but it starts to grow on me.

What we definitely need is interaction, i.e. brushing and linking of all the plots in one column, so the lines for the currently selected cell are highlighted in the marginal lineplots (otherwise I'm lacking the context).

It would be also nice to be able to filter/brush certain lines in the detail view, and see them highlighted in the heatmaps.

Maybe even show both marginal plots (row- and columnwise aggretage linechart) in the detail view so one has the context.

**Comment by mstreit** [comment]
...'it starts to grow on me' ;-)

yes, I agree that interaction is crucial.
@NMO13, if you use the Phovea heatmaps, they should support linking and brushing out of the box. @thinkh can you tell more about it tomorrow.

**Comment by thinkh** [comment]
I close this issues, since we decided to implement the heatmap approach for the conf matrix (see #108) and the bar chart for single epoch will be discussed in #109.
