### ISSUE TITLE
Update layout for image detail view for multiple datasets

### ISSUE THREAD

**Issue by mstreit** [Caleydo/malevo#96]
Images don't show up on https://malevo-daily.caleydoapp.org/

**Comment by mstreit** [comment]
Aha interesting, now it works. But the layout need to be fixed. Changed the title of this issue accordingly.

**Comment by thinkh** [comment]
Currently it looks like this: 

![grafik](https://user-images.githubusercontent.com/5851088/38998544-0d01f538-43f0-11e8-81a3-bbf93b20047d.png)

The style needs to be improved.

**Comment by thinkh** [comment]
Done with PR.
