### ISSUE TITLE
Improve line chart detail view x-axis labels

### ISSUE THREAD

**Issue by mstreit** [Caleydo/malevo#97]
Show the epoch number only instead of 'epoch X'. This will make it easier to read.

![image](https://user-images.githubusercontent.com/4129755/37951566-20c7fd16-319d-11e8-98c2-a65ce56f9194.png)

**Comment by mstreit** [comment]
Also, the label above the plot suggests that the precision is shown in percent - although it's a number between 0-1 according to the y-axis label.

**Comment by thinkh** [comment]
Done with https://github.com/Caleydo/malevo/pull/148.
