### ISSUE TITLE
use Lineup as additional detail view 

### ISSUE THREAD

**Issue by gfrogat** [Caleydo/malevo#98]
would be one possibility how to deal with non-image data and extract additional information from false positives

**Comment by mstreit** [comment]
LineUp can also deal with images that are loaded lazy from a server. See this demo with the chemical structure images:
https://chemistry.app.datavisyn.io

**Comment by mstreit** [comment]
That might be a good way to deal with a large amount of images. We could precalculate scores, rank them by the scores and use the lazy LineUp column to fetch them  from the server.

**Comment by gfrogat** [comment]
Not relevant as we don't cover the instance-based view in this version.
